Latest roxido framework

diff --git a/salso/justfile b/salso/justfile
--- a/salso/justfile
+++ b/salso/justfile
@@ -11,15 +11,23 @@ roxygen2:
   Rscript -e "roxygen2::roxygenise()"
 
 api:
-  cd src/rust/roxido; cargo doc --open
+  roxido api
 
 delete-release tag:
   git push --delete origin {{tag}}
   git tag -d {{tag}}
 
-new-release:
-  -just delete-release `date +"v%y.%m.%d"`
+date := `date +"%y.%m.%d"`
+
+new-release: check-clean
+  -just delete-release v{{date}}
   -just delete-release latest
-  git tag `date +"v%y.%m.%d"`
+  git tag v{{date}}
   git tag latest
   git push --tags
+
+check-clean:
+  @if [ -n "$(git status --porcelain)" ]; then \
+    echo "Uncommitted changes detected! Aborting."; \
+    exit 1; \
+  fi
